myplace/urls.py
from django.conf.urls import url

from . import views
app_name='myplace'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^details/(?P<select_id>[0-9]+)$', views.details, name='details'),
    url(r'^catalog/$', views.catalog, name='catalog'),
    url(r'^thefilter/(?P<typenaja>[A-Za-z ]+)$', views.thefilter, name='thefilter'),
    url(r'^about/$', views.about, name='about'),
]

place/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('myplace.urls')),
    url(r'^admin/', admin.site.urls),
]

myplace/models.py
from __future__ import unicode_literals

from django.db import models

class Place(models.Model):
      place_name              = models.CharField(max_length=200)
      place_thai_name         = models.CharField(max_length=200)
      place_type              = models.CharField(max_length=200)
class Type(models.Model):
      types                   = models.CharField(max_length=200)
      

myplace/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Place , Type


def index(request):
    image = Place.objects.all()
    the_type = Type.objects.all()
    return render(request,'myplace/index.html',{'image':image,'the_type':the_type})

def details(request , select_id):
    picture = get_object_or_404(Place, pk=select_id)
    the_type = Type.objects.all()
    data1 = "myplace/static/myplace/" + str(picture.place_name) + "/p1.txt"
    data2 = "myplace/static/myplace/" + str(picture.place_name) + "/p2.txt"
    data3 = "myplace/static/myplace/" + str(picture.place_name) + "/p3.txt"
    block1  = open(data1, "r").read()
    block2  = open(data2, "r").read()
    block3  = open(data3, "r").read()
    return render(request,'myplace/details.html',{'picture':picture, 'block1':block1, 'block2':block2, 'block3':block3,'the_type':the_type})

def catalog(request):
    image = Place.objects.all()
    the_type = Type.objects.all()
    return render(request,'myplace/catalog.html',{'image':image,'the_type':the_type})

def thefilter(request, typenaja):
    image = Place.objects.filter(place_type=typenaja)
    the_type = Type.objects.all()
    
    return render(request,'myplace/catalog.html',{'image':image,'the_type':the_type})

def about(request):
    the_type = Type.objects.all()
    return render(request,'myplace/about.html',{'the_type':the_type}) 

myplace/templates/myplace/about.html
<html>
<head>
<title>W3.CSS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<body>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'myplace/abouts-style.css' %}" />
<ul>
  <li><a href="{% url 'myplace:index' %}" method="get">Home</a></li>
  <li><a href="{% url 'myplace:catalog' %}" method="get">Catalog</a></li>
  <li class="dropdown">
    <a href="javascript:void(0)" class="dropbtn">Type</a>
    <div class="dropdown-content">
      {% for type in the_type %}
      <a href="{% url 'myplace:thefilter' type.types  %}" method="get">{{ type.types }}</a>
      {% endfor %}
    </div>
  </li>
   <li class="right"><a href="{% url 'myplace:about' %}" method="get">About</a></li>
</ul>
<div>
<img src="{% static "myplace/sea.jpg" %}" style="width:100%;height:75%" />
<div class="w3-display-middle blackbox "><b><p align="center" style="font-size:84px;" >ABOUT ME</b></p>
</div>
</div>
<br><br>

<center><div style="width:850px;border:15px solid black;padding:30px;border-color:#FAAC58;background-color:#FF4000;">
<p align="center" style="font-size:26px;color:white;">ที่กระผมสร้างเว็บไซต์นี้ขึ้นมานั้น เพื่อเป็นการศึกษา framework ชื่อ django โดยได้สร้างเป็นเว็บไซต์เกี่ยวกับสถานที่ท่องเที่ยวในกรุงเทพ </p>
</div></center>
<br>
<div>
<img src="{% static "myplace/index.png" %}" style="width:620px;height:350px;margin:10px;"class="left" />
<img src="{% static "myplace/loom.png" %}" style="width:620px;height:350px;margin:10px;"class="right" />
</div>
<div>
<center><p style="margin:25px;font-size:20px;color:#FF4000;padding-top:20px;">โดยภายในเว็บไซต์ จะแสดงสถานที่ท่องเที่ยวต่างๆที่น่าสนใจในกรุงเทพมหานคร พร้องข้อมูล อาทิ ที่ตั้ง เวลาเปิด - ปิด บริการเป็นต้น พร้อมรายละเอียด พอสังเขปของสถานที่นั้นๆ โดยได้แบ่งประเภท ของสถานที่ท่องเที่ยวไว้ เพื่อให้ง่ายต่อการค้นหา </p>
</div></center>
<br>
<div>
<center><img src="{% static "myplace/type.png" %}" style="width:750px;height:450px;" /></center>
<br>
</div>
<center><div style="width:650px;height:100px;border:10px solid black;padding:1px;border-color:#FAAC58;background-color:#FF4000;">
<p style="margin:25px;font-size:24px;color:white;">สามารถเลือกประเภท ของสถานที่ท่องเที่ยวที่สนใจได้ </b></center>
</div>
<div>
<img src="{% static "myplace/details.png" %}" style="width:620px;height:350px;margin:10px;" class="left"/>
<img src="{% static "myplace/catalog.png" %}" style="width:620px;height:350px;margin:10px;" class="right"/>
<br>
<center><p style="margin:25px;font-size:20px;color:#FF4000;padding-left:70px;padding-right:70px;">เมื่อเลือกสถานที่ที่สนใจแล้ว จะแสดงข้อมูลของสถานที่นั้นๆ อาทิ เวลา ทำการ สถานที่ตั้ง เป็นต้น
หรือสามารถ ดูสถานที่ทั้งหมดในเว็บไซต์นี้ก็ได้ </b></center>
</div>


</body>
</html>

myplace/templates/myplace/catalog.html
<html>
<head>
</head>
<body>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'myplace/catalog-style.css' %}" />
<ul>
  <li><a href="{% url 'myplace:index' %}" method="get">Home</a></li>
  <li><a href="{% url 'myplace:catalog' %}" method="get">Catalog</a></li>
  <li class="dropdown">
    <a href="javascript:void(0)" class="dropbtn">Type</a>
    <div class="dropdown-content">
      {% for type in the_type %}
      <a href="{% url 'myplace:thefilter' type.types  %}" method="get">{{ type.types }}</a>
      {% endfor %}
    </div>
  </li>
<li class="right"><a href="{% url 'myplace:about' %}" method="get">About</a></li>
</ul>
<table>
<tr>
{% for select in image %}
{% if forloop.counter <= 3 %}
<td><a href="{% url 'myplace:details' select.id %}" method="get">
  <center><img src="{% static '/myplace/' %}{{ select.place_name }}/index.jpg" style="width:400px;height:250px" /></center>
</a><br>
<b><center><div class="blackbox" style="width:370px;height:65px">{{ select.place_thai_name }}</center></div></b>
</div>
</td>
{% endif %}
{% endfor %}
</tr>
<tr>
{% for select in image %}
{% if forloop.counter > 3 and forloop.counter <= 6 %}
<td><a href="{% url 'myplace:details' select.id %}" method="get">
  <center><img src="{% static '/myplace/' %}{{ select.place_name }}/index.jpg" style="width:400px;height:250px" /></center>
</a><br>
<b><center><div class="blackbox" style="width:370px;height:65px">{{ select.place_thai_name }}</center></div></b>
</div>
</td>
{% endif %}
{% endfor %}
</tr>
<tr>
{% for select in image %}
{% if forloop.counter > 6 and forloop.counter <= 9 %}
<td><a href="{% url 'myplace:details' select.id %}" method="get">
  <center><img src="{% static '/myplace/' %}{{ select.place_name }}/index.jpg" style="width:400px;height:250px" /></center>
</a><br>
<b><center><div class="blackbox" style="width:370px;height:65px">{{ select.place_thai_name }}</center></div></b>
</div>
</td>
{% endif %}
{% endfor %}
</tr>
<tr>
{% for select in image %}
{% if forloop.counter > 9 and forloop.counter <= 12 %}
<td><a href="{% url 'myplace:details' select.id %}" method="get">
  <center><img src="{% static '/myplace/' %}{{ select.place_name }}/index.jpg" style="width:400px;height:250px" /></center>
</a><br>
<b><center><div class="blackbox" style="width:370px;height:65px">{{ select.place_thai_name }}</center></div></b>
</div>
</td>
{% endif %}
{% endfor %}
</tr>
</body>
</html>

myplace/templates/myplace/details.html
<html>
<head>
</head>
<body>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'myplace/details-style.css' %}" />
<ul>
  <li><a href="{% url 'myplace:index' %}" method="get">Home</a></li>
  <li><a href="{% url 'myplace:catalog' %}" method="get">Catalog</a></li>
  <li class="dropdown">
    <a href="javascript:void(0)" class="dropbtn">Type</a>
    <div class="dropdown-content">
      {% for type in the_type %}
      <a href="{% url 'myplace:thefilter' type.types  %}" method="get">{{ type.types }}</a>
      {% endfor %}
    </div>
  </li>
<li class="right"><a href="{% url 'myplace:about' %}" method="get">About</a></li>
</ul>
<br>
<div class="back" style="height:400px;">
<img class="left" src="{% static '/myplace/' %}{{ picture.place_name }}/picture1.jpg" />
<br>
<p>{{ block1 }}</p>

<br>
  </div>

</div>
<br>
<div class="back" style="height:400px;">
<img class="right" src="{% static '/myplace/' %}{{ picture.place_name }}/picture2.jpg" />
<br>
<p>{{ block2 }}</p>


</div>
<br>
<div class="back" style="height:400px;">
<img class="left" src="{% static '/myplace/' %}{{ picture.place_name }}/picture3.jpg" />
<br>
<p>{{ block3 }}</p>

</div>


</body>
</html>

myplace/templates/myplace/index.html
<html>
<head>
<title>W3.CSS</title>
<meta name="viewport" content="width=device-width, initial-scale=1,">

</head>

<script>
var slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("dot");
  if (n > slides.length) {slideIndex = 1}    
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";  
  }
  for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";  
  dots[slideIndex-1].className += " active";
}
</script>

<body>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'myplace/index-style.css' %}" />
<ul>
  <li><a href="{% url 'myplace:index' %}" method="get">Home</a></li>
  <li><a href="{% url 'myplace:catalog' %}" method="get">Catalog</a></li>
  <li class="dropdown">
    <a href="javascript:void(0)" class="dropbtn">Type</a>
    <div class="dropdown-content">
      {% for type in the_type %}
      <a href="{% url 'myplace:thefilter' type.types  %}" method="get">{{ type.types }}</a>
      {% endfor %}
    </div>
  </li>
  <li class="right"><a href="{% url 'myplace:about' %}" method="get">About</a></li>
</ul>

<br>

<div class="slideshow-container">
{% for select in image %}
{% if forloop.counter == 1 %}
<div class="mySlides fade" style="display:block;">
{% else %}
<div class="mySlides fade" style="display:none;">
{% endif %}
 <a href="{% url 'myplace:details' select.id %}" method="get">
  <img src="{% static '/myplace/' %}{{ select.place_name }}/index.jpg" />
</a><br>
  <b><center><div class="blackbox">{{ select.place_thai_name }}</div></center></b>
</div>
{% endfor %}


<a class="prev" onclick="plusSlides(-1)"><span style="font-size:50px">&#10094;</a></span>
<a class="next" onclick="plusSlides(1)"><span style="font-size:50px">&#10095;</a></span>

</div>
<br>

<div style="text-align:center">
  <span class="dot" onclick="currentSlide(1)"></span> 
  <span class="dot" onclick="currentSlide(2)"></span> 
  <span class="dot" onclick="currentSlide(3)"></span>
  <span class="dot" onclick="currentSlide(4)"></span>
  <span class="dot" onclick="currentSlide(5)"></span>
  <span class="dot" onclick="currentSlide(6)"></span> 
  <span class="dot" onclick="currentSlide(7)"></span> 
  <span class="dot" onclick="currentSlide(8)"></span>
  <span class="dot" onclick="currentSlide(9)"></span>
  <span class="dot" onclick="currentSlide(10)"></span>    
</div>

</body>
</html>